import { z } from "zod";

// Minimal, permissive schema that matches the autogenerated __registry__/Index shape.
export const registryFileSchema = z.object({
  path: z.string(),
  type: z.string().optional(),
  target: z.string().optional(),
});

export const registryItemSchema = z.object({
  name: z.string(),
  description: z.string().optional(),
  type: z.string().optional(),
  registryDependencies: z.array(z.string()).optional(),
  files: z.array(z.union([z.string(), registryFileSchema])).optional(),
  component: z.any().optional(),
  meta: z.any().optional(),
});

export type RegistryItem = z.infer<typeof registryItemSchema>;
